[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_product_listing = "6wuLk2iZ7gca4t3nbNiZYjspFEr8L9xGDwWeMAhojPMw"

[programs.devnet]
solana_product_listing = "6wuLk2iZ7gca4t3nbNiZYjspFEr8L9xGDwWeMAhojPMw"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
